### ISSUE TITLE
Serving an HDT file sometimes throws a LOGArray error

### ISSUE THREAD

**Issue by RinkeHoekstra** [LinkedDataFragments/Server.js#10]
When serving an HDT file, the server sometimes throws the following error:

`Error: Trying to read a LOGArray but data is not LogArray`

It is unclear whether this is a problem with the HDT GUI (from http://www.rdfhdt.org), or the linked data fragments server. For instance, the SWDF HDT dataset http://gaia.infor.uva.es/hdt/swdf-2012-11-28.hdt.gz  loads fine in the server, but cannot be opened using the GUI. 

A test file can be downloaded from: https://www.dropbox.com/s/mumhgkt4fazbk8s/clariah-canada-1901.hdt?dl=0

**Comment by pietercolpaert** [comment]
:+1: for documenting this in the README.md!

**Comment by RubenVerborgh** [comment]
Note that the above workaround is no longer needed starting from v1.4.0 of the Node.js hdt module, as index files now have a versioned suffix (e.g., `hdt.index.v1-1`
