### ISSUE TITLE
Server does not pick up HDT files specified in the config

### ISSUE THREAD

**Issue by jaw111** [LinkedDataFragments/Server.js#112]
I am running the server locally on Win10 in WSL and have a local HDT file on the mounted drive.

My config looks like this:

```
{
  "title": "Tryout",
  "datasources": {
    "myHDT": {
      "title": "Test",
      "type": "HdtDatasource",
      "description": "Some test data",
      "settings": { "file": "data/test.hdt" }
    }
  }
}
```

The server starts, but there are only 7 'metadata' statements available, nothing from the HDT.

**Comment by rubensworks** [comment]
I assume you are visiting the index of the server (something like http://localhost:3000/), and not the HDT datasource itself. For that, you'll have to go to http://localhost:3000/myHDT.

**Comment by jaw111** [comment]
Thanks, that works fine.

Is it possible to specify an array of HDT files to use as a datasource, or does one need to use a composite datasource to achieve that?

**Comment by rubensworks** [comment]
Yes, you need a composite datasource for combining multiple files.

**Comment by jaw111** [comment]
Thanks, composite datasource works as expected.
