### ISSUE TITLE
Server crashes on empty HDT file

### ISSUE THREAD

**Issue by LaurensRietveld** [LinkedDataFragments/Server.js#13]
Publishing empty HDT files crashes the server. Error message:
`terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc`

I know, publishing empty HDT files is not a common thing to do ;). However, when publishing many datasets, situations like this may occur.

**Comment by RubenVerborgh** [comment]
Thanks for reporting! That's probably something the HDT library needs to fix. I'll investigate!

**Comment by RubenVerborgh** [comment]
[Fixed in the original HDT C++ library](https://github.com/rdfhdt/hdt-cpp/pull/8); this bugfix is present in [HDT-Node v1.1.1](https://github.com/RubenVerborgh/HDT-Node/tree/v1.1.1).

To upgrade:
```
cd Server.js
rm -r node_modules/hdt
npm install
```
