### ISSUE TITLE
Error: Cannot find module 'rdf-string' in core package

### ISSUE THREAD

**Issue by mielvds** [LinkedDataFragments/Server.js#131]
I'm in the process of migrating an [a datasource implementation that indexes summaries](https://github.com/mielvds/ldf-datasource-summary) to 3.0. I get the following error when importing the @ldf/core package:

```
Error: Cannot find module 'rdf-string'
Require stack:
- /Users/mielvandersande/Meemoo/NDE/demo/datasource-summary/node_modules/@ldf/core/lib/datasources/Datasource.js
- ...
```

It seems  the abstract class` Datasource`  is using the `rdf-string` module: https://github.com/LinkedDataFragments/Server.js/blob/master/packages/core/lib/datasources/Datasource.js#L8
However, it is not mentioned in the core package's dependencies: https://github.com/LinkedDataFragments/Server.js/blob/master/packages/core/package.json#L37. Shouldn't this be the case? Or is this issue caused by something missing at my end?

**Comment by rubensworks** [comment]
Heh, weird we didn't catch that before yet. Looks like a missing dependency indeed.

**Comment by mielvds** [comment]
Because `@ldf/core` is mostly used in conjuction with `@ldf/feature-qpf` that does import `rdf-string`, it probably went unnoticed :) Thanks for picking this up!
