### ISSUE TITLE
Invalid path to components file

### ISSUE THREAD

**Issue by mielvds** [LinkedDataFragments/Server.js#134]
This issue is probably more related to how [Components.js](https://www.npmjs.com/package/componentsjs) works, but because of the context and pinpoint the why, I'm posting it here.

I'm trying to configure an LDF server that simply adds the datasource module from https://github.com/mielvds/ldf-datasource-summary. I used https://github.com/LinkedDataFragments/Server.js/tree/master/packages/server to get something going. (I looked at https://github.com/LinkedDataFragments/Server.js/tree/master/packages/preset-qpf, but that's basically the same?) The package.json looks like this:

``` json
{
  "name": "@ldf/server",
  "description": "Quad Pattern Fragments Linked Data Fragments Server",
  "version": "3.0.9",
  "lsd:module": "https://linkedsoftwaredependencies.org/bundles/npm/@ldf/server",
  "lsd:contexts": {
    "https://linkedsoftwaredependencies.org/bundles/npm/@ldf/server/^3.0.0/components/context.jsonld": "components/context.jsonld"
  },
  "lsd:importPaths": {
    "https://linkedsoftwaredependencies.org/bundles/npm/@ldf/server/^3.0.0/components/": "components/",
    "https://linkedsoftwaredependencies.org/bundles/npm/@ldf/server/^3.0.0/config/": "config/"
  },
  "license": "MIT",
  "bin": {
    "ldf-server": "./bin/ldf-server",
  },
  "publishConfig": {
    "access": "public"
  },
  "files": [
    "components",
    "config",
    "lib/**/*.js",
    "bin/**/*",
    "index.js"
  ],
  "scripts": {
    "test": "nyc mocha",
    "lint": "eslint bin/* lib test"
  },
  "dependencies": {
    "@ldf/core": "^3.0.7",
    "@ldf/datasource-composite": "^3.0.7",
    "@ldf/datasource-hdt": "^3.0.9",
    "@ldf/datasource-jsonld": "^3.0.7",
    "@ldf/datasource-n3": "^3.0.8",
    "@ldf/datasource-sparql": "^3.0.7",
    "@ldf/feature-memento": "^3.0.7",
    "@ldf/feature-qpf": "^3.0.7",
    "@ldf/feature-summary": "^3.0.7",
    "@ldf/preset-qpf": "^3.0.0",
    "ldf-datasource-summary": "0.0.1"
  }
}
```

When running `./bin/ldf-server`, it seems to construct the path to the components file by concatenating two absolute file paths:
```
Error: Invalid components file "<dir_where_server_is>/node_modules/ldf-datasource-summary/components/<dir_where_server_is>/node_modules/ldf-datasource-summary/components/components.jsonld":
```

How are these paths constructed? Anything I missed in https://github.com/mielvds/ldf-datasource-summary/tree/master/components or https://github.com/mielvds/ldf-datasource-summary/blob/master/package.json?

**Comment by rubensworks** [comment]
Your path is in fact correct, it's only the error message that incorrectly constructucts the path (this will be fixed soon in a Components.js rewrite).

What is the full error you are getting? That _should_ show more information about what is going wrong.

----

Side-note, have you seen [this](https://github.com/LinkedDataFragments/Server.js/tree/master/packages/feature-summary)? This is ported from code you wrote before.

**Comment by mielvds** [comment]
> Your path is in fact correct, it's only the error message that incorrectly constructucts the path (this will be fixed soon in a Components.js rewrite).
> 
> What is the full error you are getting? That _should_ show more information about what is going wrong.
> 

I get a second error indeed, which I thought was unrelated: 
``` 
 jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.

...

details: 
{
      code: 'loading remote context failed',
      url: 'https://linkedsoftwaredependencies.org/bundles/npm/ldf-datasource-summary/^0.0.1/components/context.jsonld',
      cause: [JsonLdError]
    }
```

https://linkedsoftwaredependencies.org/bundles/npm/ldf-datasource-summary/0.0.1/components/context.jsonld returns a 500, but regardless, I thought Components.js checks the local filesystem first?

> Side-note, have you seen [this](https://github.com/LinkedDataFragments/Server.js/tree/master/packages/feature-summary)? This is ported from code you wrote before.

Jep! But that's a different thing, ie. publishing the summaries. This module is to use summaries as a datasource, more of a niche application.

**Comment by rubensworks** [comment]
> I thought Components.js checks the local filesystem first?

Indeed, it should.
Your package.json, config file and components files look fine to me, so perhaps something is going wrong when starting the server.

I suspect your config is being loaded, but your `ldf-datasource-summary` was not detected by Components.js.
This could be because it is not part of the `node_modules` folder the main module path (usually location of the server package).

If you are using `@ldf/server`, then you'll have to add `ldf-datasource-summary` to its dependencies (`npm link` should be fine as well).
A better approach would be to fork `@ldf/server` into a dedicated npm package that you can optionally re-publish, and add the dependency there.

**Comment by rubensworks** [comment]
FYI, we just discovered that `npx` may also be a good tool for this: https://github.com/LinkedSoftwareDependencies/Components.js/issues/29#issuecomment-756060555

**Comment by mielvds** [comment]
Thanks @rubensworks. I

**Comment by mielvds** [comment]
Thanks @rubensworks. The issue persists, even with npm link (or npx)... could you explain what you mean with fork? I have my own 'copy' of @ldf/server where I edited the package.json and config.json. 
I've put the files [here](https://github.com/mielvds/summary-server), maybe you can reproduce?

**Comment by rubensworks** [comment]
I may be missing something, but the server seems to be starting without issues for me when using your repos.

My steps:
1. Clone and install the two repos
2. Npm link `ldf-datasource-summary` into `summary-server`.
3. Execute `node bin/ldf-server config/config-example.json` with the following config contents (original one does not seem to include the summary datasource):

```
{
  "@context": "https://linkedsoftwaredependencies.org/bundles/npm/@ldf/server/^3.0.0/components/context.jsonld",
  "@id": "urn:ldf-server:my",
  "import": "preset-qpf:config-defaults.json",

  "title": "My Linked Data Fragments server",

  "datasources": [
    {
      "@id": "ex:myHdtDatasource",
      "@type": "HdtDatasource",
      "datasourceTitle": "DBpedia 2014",
      "description": "DBpedia 2014 with an HDT back-end",
      "datasourcePath": "dbpedia",
      "hdtFile": "data/dbpedia2014.hdt"
    },
    {
      "@id": "ex:mySparqlDatasource",
      "@type": "SparqlDatasource",
      "datasourceTitle": "DBpedia (Virtuoso)",
      "description": "DBpedia with a Virtuoso back-end",
      "datasourcePath": "dbpedia-sparql",
      "sparqlEndpoint": "https://dbpedia.org/sparql"
    },
    {
      "@id": "ex:register",
      "@type": "SummaryDatasource",
      "datasourceTitle": "Summary register for source selection",
      "description": "My dataset with a Summaries back-end",
	  "datasourcePath": "summary",
      "dir": "/received-summaries"
    }
  ]
}
```

**Comment by rubensworks** [comment]
@mielvds FYI, I've justed updated the server (3.2.0) to Components.js v4, which may simplify things on your end.
Configs are fully backwards-compatible.

**Comment by mielvds** [comment]
Thx @rubensworks , the error messages are much clearer now for debugging. Can't get it to work though and i have no idea why it works for you. 

Right now, I get:

```
2021-01-20T15:18:09.309Z [Components.js] warn: Detected remote context lookup for 'https://linkedsoftwaredependencies.org/bundles/npm/ldf-datasource-summary/^0.0.1/components/context.jsonld' in /Users/mielvandersande/Meemoo/NDE/demo/datasource-summary/components/components.jsonld. This may indicate a missing or invalid dependency, or an invalid context URL.
```
If I replace the link in `ldf-datasource-summary/components/components.jsonld` directly with the context

```
{
  "@context": [
    "https://linkedsoftwaredependencies.org/bundles/npm/componentsjs/^4.0.0/components/context.jsonld",
    {
      "npmd": "https://linkedsoftwaredependencies.org/bundles/npm/",
      "ldfdsm": "npmd:ldf-datasource-summary/",
      "files-ldfdsm": "ldfdsm:^0.0.1/",

      "SummaryDatasource": "ldfdsm:Datasource/Summary"
    }
  ],
  "@id": "npmd:ldf-datasource-summary",
  "@type": "Module",
  "requireName": "ldf-datasource-summary",
  "import": [
    "files-ldfdsm:components/Datasource/Summary.jsonld"
  ]
}
```
I get `Component definition error:
Error: Error while parsing file "https://linkedsoftwaredependencies.org/bundles/npm/ldf-datasource-summary/^0.0.1/components/Datasource/Summary.jsonld": Unexpected "T" at position 0 in state STOP` Here I'm completely lost I'm afraid :)

**Comment by rubensworks** [comment]
This might be due to the usage of `"lsd:module": true`, which expands to a context URL that only includes the major version of your package (in your case `^0.0.0`).

Could you try applying the following change in your components file?
``` diff
- "files-ldfdsm": "ldfdsm:^0.0.1/",
+ "files-ldfdsm": "ldfdsm:^0.0.0/",
```

I can have another look at it tomorrow if things would still not work after this.

**Comment by mielvds** [comment]
yes, that did it! Almost there ;)

Now it just needs to pick up the parameters:

```
Component definition error:
Error: Error while parsing file "config.json": Invalid predicate IRI: dir
```

With config.json:

``` json
{
  "@context": [
    "https://linkedsoftwaredependencies.org/bundles/npm/@ldf/server/^3.0.0/components/context.jsonld",
    "https://linkedsoftwaredependencies.org/bundles/npm/summary-server/^0.0.0/components/context.jsonld"],
  "@id": "urn:ldf-server:my",
  "import": "preset-qpf:config-defaults.json",

  "title": "My Linked Data Fragments server",

  "datasources": [
    {
      "@id": "ex:register",
      "@type": "SummaryDatasource",
      "datasourceTitle": "Summary register for source selection",
      "description": "My dataset with a Summaries back-end",
	    "datasourcePath": "summary",
      "dir": "/received-summaries"
    }
  ]
}

```

**Comment by rubensworks** [comment]
`dir` should probably be `ldfdsm:Datasource/Summary#dir` (unless you add an entry for it in your [context](https://github.com/mielvds/ldf-datasource-summary/blob/master/components/context.jsonld)).

**Comment by mielvds** [comment]
ah yes, now I understand and it works. I wrongfully thought 

```
      "constructorArguments": {
        "@id": "ldfdsm:Datasource/Summary#constructorArgumentsObject",
        "extends": "ldfc:Datasource#constructorArgumentsObject",
        "fields": [
          {
            "keyRaw": "dir",
            "value": "ldfdsm:Datasource/Summary#dir"
          }
        ]
      }
```
was taking care of that.

Thx @rubensworks !
