### ISSUE TITLE
Support https:// URLs

### ISSUE THREAD

**Issue by RubenVerborgh** [LinkedDataFragments/Server.js#17]
Reported by @warpr in #9:

In my case the configured baseURL is "https://licensedb.org/data/", the generated links look like "http://licensedb.org/data/licensedb#dataset" and "http://licensedb.org/data/licensedb?page=2".

I have set up a 301 redirect from http to https, so it isn't much of a practical problem right now -- but obviously it would be nicer if those links didn't go via http://. A front-end proxy does the SSL termination, so the connection between the browser and the front-end proxy is SSL, but the connection between the proxy and the LDF server is plain http.

**Comment by RubenVerborgh** [comment]
Thanks for finding this @warpr, it was an important issue that (despite the limited lines of code affected) took me all morning to fix. Basically, the base URL was not honored in the `LinkedDataFragmentsServer` class (which generates the page and redirect URLs), only in the fragment writers.

Can you verify that 64d1f749f05f15584f1cf9145f9721be3b6300a9 indeed fixes your problem? If so, I will do a new patch release.

**Comment by warpr** [comment]
@RubenVerborgh thanks for the quick fix!  I'm going to try it today and report back.

**Comment by warpr** [comment]
@RubenVerborgh yes, I deployed the develop branch and that has fixed the problem.  Thanks again! :shipit:

**Comment by RubenVerborgh** [comment]
Alright, thanks for testing. Released as [1.1.6](https://github.com/LinkedDataFragments/Server.js/releases/tag/v1.1.6).
