### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by oman-ispace** [LinkedDataFragments/Server.js#18]
Hi,

This could be an error, or it could be my lack of kowledge about Node.js

when trying to install the ldf-server using 'npm' I get a error message:
============================================================================
npm ERR! Error: failed to fetch from registry: ldf-server
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/ispace/Documents/programming/nodeJS/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.13.0-57-generic
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "ldf-server"
npm ERR! cwd /home/ispace/Documents/programming/nodeJS
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: ldf-server

npm ERR! Error: EACCES, permission denied 'npm-debug.log'
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! 
npm ERR! System Linux 3.13.0-57-generic
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "ldf-server"
npm ERR! cwd /home/ispace/Documents/programming/nodeJS
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! path npm-debug.log
npm ERR! code EACCES
npm ERR! message EACCES, permission denied 'npm-debug.log'
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ispace/Documents/programming/nodeJS/npm-debug.log
npm not ok
============================================================================

**Comment by mielvds** [comment]
There seem to be two issues:
a) this is a recent `npm` issue that is popping up here and there. 
What's your npm version? `npm -v`
Switching to http instead of https sometimes works, but is more of a hack. `npm config set registry http://registry.npmjs.org/`
b) you don't have the right permissions to do a global install with `-g`. Have you tried running with sudo?

**Comment by oman-ispace** [comment]
Hi

The npm version is 1.1.4

Here is what I get when I run npm with sudo:

npm http GET https://registry.npmjs.org/ldf-server

npm ERR! Error: failed to fetch from registry: ldf-server
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/ispace/Documents/programming/nodeJS/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.13.0-57-generic
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "ldf-server"
npm ERR! cwd /home/ispace/Documents/programming/nodeJS
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: ldf-server
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ispace/Documents/programming/nodeJS/npm-debug.log

**Comment by mielvds** [comment]
Are you on ubuntu? Because node 0.6.12 and npm 1.1.4 are very outdated (those packages don't seem to ever change). I recently ran into the exact same issues, try this:

    apt-add-repository ppa:chris-lea/node.js
    apt-get update
    apt-get install -y nodejs
    apt-get install -y npm
    npm install -g node-gyp # Install the "node-gyp" globally.

**Comment by oman-ispace** [comment]
This seems to have solved the issue. However when running the command 'apt-get install -y npm' I got the following issue:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 npm : Depends: nodejs but it is not going to be installed
       Depends: nodejs-dev
       Depends: node-request but it is not going to be installed
       Depends: node-mkdirp but it is not going to be installed
       Depends: node-minimatch but it is not going to be installed
       Depends: node-semver but it is not going to be installed
       Depends: node-ini but it is not going to be installed
       Depends: node-graceful-fs but it is not going to be installed
       Depends: node-abbrev but it is not going to be installed
       Depends: node-nopt but it is not going to be installed
       Depends: node-fstream but it is not going to be installed
       Depends: node-rimraf but it is not going to be installed
       Depends: node-tar but it is not going to be installed
       Depends: node-which but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

It seems that it is a problem with apt repository.

**Comment by mielvds** [comment]
That's ok, that command is obsolete anyway (npm is part of nodejs package). Anyway, I'll close this now, since these aren't really ldf-server issues. Thanks for sharing though!
