### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by mgns** [LinkedDataFragments/Server.js#19]
I have trouble installing the ldf-server due to dependencies. Being not proficient with NodeJS the error reports and dependencies just look unfamiliar when setting up the environment. It would be helpful to have a Dockerfile. My approach does not work fully:

```
FROM ubuntu:14.10

RUN apt-get install -y software-properties-common
RUN apt-add-repository ppa:chris-lea/node.js
RUN apt-get update
RUN apt-get install -y nodejs
RUN apt-get install -y python

#RUN npm install hdt

# Bundle app source
ADD . /src

# Install app dependencies
RUN cd /src; npm install -g ldf-server

EXPOSE 5000

WORKDIR /src
CMD ldf-server config.json 5000 4
```

**Comment by RubenVerborgh** [comment]
A Dockerfile is indeed something that was on my feature list.

Could you explain what does not work with your approach?

**Comment by mgns** [comment]
make, g++ and git was missing. Now it works! Reading error messages entirely sometimes helps.

```
FROM ubuntu:14.10

RUN apt-get install -y software-properties-common
RUN apt-add-repository ppa:chris-lea/node.js
RUN apt-get update
RUN apt-get install -y nodejs
RUN apt-get install -y python make g++ git

#RUN npm install hdt

# Bundle app source
ADD . /src

# Install app dependencies
RUN cd /src; npm install -g ldf-server

EXPOSE 5000

WORKDIR /src
CMD ldf-server config.json 5000 4
```

**Comment by RubenVerborgh** [comment]
Alright, thanks! Now we just need to find a way to make adding datasets easy.

**Comment by mgns** [comment]
I preferred using the HDT approach and mounted a local folder to /src/data on startup. That allows to reuse the docker image, just select the data folder and final port on startup. You can also put the config.json into that data folder:
```
$ docker build -t ldfragments .
$ docker run -v /home/magnus/data:/src/data -p 5000:5000 ldfragments
```

**Comment by barthanssens** [comment]
Current docker file is a good start, but does create a rather large image. 

FYI, I'm experimenting a little bit, and using node:4-alpine won't work (at least, not when HDT module is required, because the hdt library needs to be build, just including and removing g++/python does not work either because of a missing symbol/library... working on it)

**Comment by thadguidry** [comment]
@barthanssens Alpine doesn't use glibc, but instead musl libc.  This makes it smaller, but you might run into build problems if glibc is necessary for some of the libraries.

**Comment by RubenVerborgh** [comment]
I've reassigned to @rubensworks, as he created the Dockerfile we currently have. We should probably close this issue and create a new one for the others.

**Comment by rubensworks** [comment]
Closing this issue as the server has a [Dockerfile](https://github.com/LinkedDataFragments/Server.js/blob/master/Dockerfile) and is available on the [Docker hub](https://hub.docker.com/r/linkeddatafragments/server.js/).

The issue about the Docker image size will be continued in #40.
