### ISSUE TITLE
Error when I try to install ldf server

### ISSUE THREAD

**Issue by SergioML9** [LinkedDataFragments/Server.js#21]
Hi,

I'm getting the following error when I try to install ldf server with 'sudo npm install -g ldf-server' on Mac.

![captura de pantalla 2015-11-02 a las 13 04 26](https://cloud.githubusercontent.com/assets/10586800/10881399/994d37d0-8162-11e5-9a09-7d211b0a20d5.png)

My node version is v4.1.1.

Thanks !

**Comment by RubenVerborgh** [comment]
This error occurs with Node 4.x due to an outdated dependency, which is already [fixed](cccc24fd13951061b43a7b6199edfe5ff0e7276f) in the `develop` branch.

We will release a new version soon, but for now, you will need to do `npm install LinkedDataFragments/Server.js#develop`.
