### ISSUE TITLE
MementoController Chooses TimeGate URL if no original base URL is set

### ISSUE THREAD

**Issue by hariharshankar** [LinkedDataFragments/Server.js#26]
The config file allows for an original base URL to be set using the parameter `originalBaseURL`. However, when this parameter is not set, the [MementoControllerExtension, Line 33-34](https://github.com/LinkedDataFragments/Server.js/blob/master/lib/controllers/MementoControllerExtension.js#L33) chooses the TimeGate base URL. It would be better to either make this parameter mandatory in the config when the server is in Memento mode, or, use the `baseURL` parameter in the config to construct the original URL.

**Comment by RubenVerborgh** [comment]
> It would be better to either make this parameter mandatory in the config

I'd prefer a sensible default over a mandatory parameter.

> use the baseURL parameter in the config to construct the original URL.

The trouble is: baseURL isn't mandatory either.

But how big is the problem actually? It's fixed by specifying `originalBaseURL`, right?

Another alternative is that, if `originalBaseURL` is not set, no `rel=original` link is emitted. Then we're not making any mistakes at all. What do you think?

**Comment by hariharshankar** [comment]
`rel=original` is mandatory for Mementos and TimeGates; it makes the whole cycle complete. So, we cannot omit it.

We do not have a problem when the `originalBaseURL` is specified. When it is not specified, the default we currently have is the TimeGate url, and that is wrong.

**Comment by mielvds** [comment]
It definitely shouldn't be the timegate URL.
AFAIK, the issue only occurs when the original resource is not hosted by the Server hosting the mementos. I tend to agree with Harish, it doesn't make sense not having a `originalBaseURL` specified, and omitting violates the standard. I do understand the trouble of mandatory parameters, maybe we should make the dataset not load at all?

**Comment by RubenVerborgh** [comment]
> AFAIK, the issue only occurs when the original resource is not hosted by the Server hosting the mementos.

Could you explain the situations in which a server needs/does not need `originalBaseURL`? It seems to be part of the `timegates` block. I'm a bit confused by the [instructions](https://github.com/LinkedDataFragments/Server.js/wiki/Configuring-Memento). Can/should `timegates` and `datasources` ever be used together? Perhaps the wiki page should have 2 different subsections for the two different cases (server hosting original resource / server not hosting it).

> maybe we should make the dataset not load at all?

I'm find with throwing an exception in the constructor of `MementoControllerExtension` if `originalBaseURL` is missing.

**Comment by mielvds** [comment]
> Could you explain the situations in which a server needs/does not need `originalBaseURL`?

Actually, this confuses me as well. It should be set to the location where the original resource resides. 
If we take the dbpedia example, this should simply be set to `originalBaseURL: "http://fragments.dbpedia.org/2015/en",`

So @hariharshankar second option is only the valid one: 
> use the baseURL parameter in the config to construct the original URL

E.g., `http://fragments.mementodepot.org/dbpedia` can be constructed from the `baseURL`parameter and the fact that the timegate is under key `"dbpedia"`

See #27 for a proposed fix.

**Comment by RubenVerborgh** [comment]
Thanks, #27 has been merged in the develop branch.

Perhaps we should still update the wiki to make this more clear.

**Comment by RubenVerborgh** [comment]
@hariharshankar Can you check if #27 is okay for you?

**Comment by hariharshankar** [comment]
#27 would work. 

Just making sure: when appending the `datasoure` to the `_baseUrl` in [MementoControllerExtension.js](https://github.com/LinkedDataFragments/Server.js/pull/27/files), will that pick up the "generic" key "dbpedia" under the timegates in config? Or will the datasource part of the original URL change with the datasource requested?

**Comment by mielvds** [comment]
Oh yes, you are completely right. I'll fix that

**Comment by mielvds** [comment]
Fixed in https://github.com/LinkedDataFragments/Server.js/commit/006aa0bae8a76a7fc190631e3fdb1dfa8d048a9b It's even shorter now :)

**Comment by hariharshankar** [comment]
Great! Do you want me to update the wiki, or were you planning on it?

**Comment by mielvds** [comment]
I'll have a look

**Comment by mielvds** [comment]
Wiki updated! case closed
