### ISSUE TITLE
Multiple HDT files as a datasource

### ISSUE THREAD

**Issue by migalkin** [LinkedDataFragments/Server.js#34]
I'm wondering if it's possible to specify in `config.json` multiple HDT files for one datasource?
Say, 
```
"settings": { "file":["/data/dump1.hdt", "/data/dump2.hdt"] }
```
but didn't work for me.

**Comment by rubensworks** [comment]
The `CompositeDatasource` allows you to combine several datasources in one.
Here's an example config file which combines several datasource types, but you can use it as well to just combine several HDT files: https://github.com/LinkedDataFragments/Server.js/blob/master/config/config-composite.json

**Comment by migalkin** [comment]
Worked fine, thank you very much!

**Comment by miranda-zhang** [comment]
Doesn't seem to work for me.
I got `WARNING: skipped datasource cocoon. Invalid filename:`
```
{
    "title": "My Linked Data Fragments server",
    "baseURL": "http://data.example.org/",
    "datasources": {
      "cocoon": {
        "title": "CoCoOn 2012",
        "type": "HdtDatasource",
        "description": "CoCoOn 2012 with an HDT back-end",
        "settings": {
            "references": [ "gcloud_vm", "gcloud_storage"]
        }
      },
      "gcloud_vm": {
        "hide": true,
        "title": "gcloud_vm HDT",
        "type": "HdtDatasource",
        "description": "A test HDT datasource",
        "settings": { "file": "gcloud_vm.hdt" }
      },
      "gcloud_storage": {
        "hide": true,
        "title": "gcloud_storage HDT",
        "type": "HdtDatasource",
        "description": "A test HDT datasource",
        "settings": { "file": "gcloud_storage.hdt" }
      }
    }
  }

```
I tested each hdt file individuly, both worked by itself.

**Comment by mielvds** [comment]
Try setting the type to CompositeDatasource of the cocoon source
