### ISSUE TITLE
Docker + HDT dataset error

### ISSUE THREAD

**Issue by migalkin** [LinkedDataFragments/Server.js#35]
I built a Docker image of the Server and supplied there an HdtDatasource in the config.json:
```
"datasources": {
    "chebi": {
      "title": "ChEBI",
      "type": "HdtDatasource",
      "description": "ChEBI HDT",
      "settings": { "file": "/data/chebi.hdt" }
    }
   },
```

then I run the container and attach volumes:
```
docker run -it -p 3001:3000 --rm -v /<path>/ChEBI/config.json:/tmp/config.json -v <path>/ChEBI/chebi.hdt:/data/chebi.hdt ldf_hdt_server /tmp/config.json
```

I get the error:
```
Master 1 running on http://localhost:3000/.
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
```

I didn't manage to trace the error to the js sources, apparently it's an error of the HDT library.
The HDT file is correct, I can query it and get hdtInfo().

Could you please give any clue how to fix it?

**Comment by RubenVerborgh** [comment]
What is the size of the ChEBI dataset? Could you share the HDT file with me in some way?

Does the error occur immediately after booting the server, or when execution requests/queries?

**Comment by migalkin** [comment]
ChEBI is taken from Fedbench, the raw size in .NT is 830 MB, HDT size is about 25 MB. 
Please find the .tar.gz'ed NT file there: https://drive.google.com/file/d/0B3uXlknE4eJrVGpWRXFuS1FOd0E/view?usp=sharing

I used HDT Java library and HDT C++ library, according to my tests, this error is thrown when working with the Java-produced dump.
Here is Java-produced chebi-java.hdt : https://drive.google.com/file/d/0B3uXlknE4eJrYkdXb2RCYktVcmM/view?usp=sharing

Here is C++-produced chebi-cpp.hdt : https://drive.google.com/file/d/0B3uXlknE4eJrVDZKbFg2Nl92OVE/view?usp=sharing

That is, when I supply chebi-java.hdt in the config.json then I get the error 
```
Master 1 running on http://localhost:3000/.
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
```
immediately after I started the docker container with the server.

When I supply the C++-produced file then it works somehow fine:
```
Master 1 running on http://localhost:3000/.
Predicate Bitmap in 87 ms 986 us
Count predicates in 111 ms 544 us
Count Objects in 1 sec 582 ms 125 us Max was: 50477
Bitmap in 198 ms 410 us
Bitmap bits: 4772706 Ones: 772138
Object references in 1 sec 794 ms 248 us
Sort lists in 370 ms 618 us
Index generated in 4 sec 146 ms 837 us
Worker 9 running on http://localhost:3000/.
```

**Comment by RubenVerborgh** [comment]
Does the Java-produced dump work when you delete the `.hdt.index` file?

Backstory: while the `.hdt` files generated by Java and C are identical, they both have their own `.hdt.index` structure to speed up lookups.

**Comment by migalkin** [comment]
No, the Java-produced dump doesn't work even being installed from scratch.

**Comment by RubenVerborgh** [comment]
Alright; then my solution would be simple in this case: always use the C++ generator. It's also what we do: `rdf2hdt -f turtle in.nt out.hdt`. (The `-f turtle` is important, as it's the only proper parser.)
Would this work for you?

Since we're not the maintainers of HDT-Java and HDT-CPP (even though we occasionally contribute to the latter), it's hard for us to help with incorrectly generated HDT files. But feel free to file a bug with HDT-Java.

**Comment by migalkin** [comment]
The HDT-CPP-produced files worked fine, thank you. Will proceed in future with the C++ lib.
