### ISSUE TITLE
setting up SSL

### ISSUE THREAD

**Issue by pheyvaer** [LinkedDataFragments/Server.js#43]
Is the `ca` required (as done in the example) or is the `key` and `cert` enough? And are there errors thrown or logs created when the keys/certs are not found?

**Comment by rubensworks** [comment]
If you configure HTTPS in your webserver (nginx/apache), then you don't need to do that again in the LDF server itself.

Just make sure you include `https://` in your baseURL inside the config file and you should be good to go.

**Comment by pheyvaer** [comment]
If I add `https` do the baseURL and remove `ssl` information I get the following error:

```
Master 232216 running on https://localhost:50000/.
_tls_common.js:89
      c.context.setCert(options.cert);
                ^

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.createSecureContext (_tls_common.js:89:17)
    at Server (_tls_wrap.js:794:25)
    at new Server (https.js:48:14)
    at Object.createServer (https.js:70:10)
    at new LinkedDataFragmentsServer (/home/pieterhe/dev/Server.js/lib/LinkedDataFragmentsServer.js:22:31)
```

**Comment by rubensworks** [comment]
Could you copy-paste your full config file here?

**Comment by pheyvaer** [comment]
```
{
  "title": "Pieter Heyvaert's TPF Server",
  "baseURL": "https://data.pieterheyvaert.com",
  "datasources": {
    "research": {
      "title": "Research",
      "type": "TurtleDatasource",
      "description": "Semantic Web and Linked Data research data.",
      "settings": { "file": "research.nt" }
    },
    "bubobu": {
      "title": "BuBoBu Library",
      "type": "TurtleDatasource",
      "description": "Library categorised as to buy, borrow, or burn.",
      "settings": { "file": "bubobu.nt" }
    }
  }
}
```

**Comment by rubensworks** [comment]
Are you using the latest version of the LDF server?

If so, is your server by any chance running on Windows? Perhaps this might have something to do with this: https://stackoverflow.com/questions/20837161/openssl-pem-routinespem-read-biono-start-linepem-lib-c703expecting-truste
Because we use a similar setup on the LDF and LSD server (Ubuntu), and those work just fine like this.

**Comment by pheyvaer** [comment]
Yes, latest version of the LDF server. I'm using CentOS 6. But I guess it is because I specific the use of `https` that it tries to read the cert, no? I provided that now (both the key and the cert). The server starts without error, but I get a 502 and that the get request could not be completed when browsing to the main page.

**Comment by rubensworks** [comment]
AFAIK the cert that is shipped by the server will be used by default, but I'm not 100% sure about that. I think something might be going wrong while reading this cert here.

@RubenVerborgh @mielvds Any ideas about this?

**Comment by pheyvaer** [comment]
But doesn't the cert need to match the one that is configured in your apache/nginx?

**Comment by pheyvaer** [comment]
This is fixed by adding `"protocol":"http"` to the config file. Might be good to add this to the documentation.

**Comment by mielvds** [comment]
We'll have to look whether we can make the config better; it seems like it's not considering some edge cases
