### ISSUE TITLE
Improve HTTP/S configuration

### ISSUE THREAD

**Issue by mielvds** [LinkedDataFragments/Server.js#48]
At the moment, the HTTPS configuration is not clear for some edge cases:
- what to do if HTTPS is handled by the proxy?
- how to produce HTTPS urls without actually running https
- etc

Todo: revise and come up with a better design to specify different HTTPS scenarios

**Comment by RubenVerborgh** [comment]
I think the design is okay, it just needs documentation:

> what to do if HTTPS is handled by the proxy?

Set `"protocol": "http"`.

>  how to produce HTTPS urls without actually running https

Set `"baseURL": "https://…"

`baseURL` is used to create the hypermedia controls and, in absence of `protocol`, determines whether the protocol will be `http` or `https`. `protocol` can override that setting.

**Comment by mielvds** [comment]
Great if we can fix this documentation wise.
To be sure, if `"baseURL": "https://…"`, the SSL logic in the server is not activated?
Or only if you explicitely set protocol to `http`?

**Comment by RubenVerborgh** [comment]
`"baseURL": "https://…"` actives HTTPS in the server.

By explicitly setting `"protocol": "http"`, you override this: https://github.com/LinkedDataFragments/Server.js/commit/7fbdae8ed7b34721e0240cbbb8a60d228144037a

**Comment by mielvds** [comment]
ok, that was missing from the readme. This should do: https://github.com/LinkedDataFragments/Server.js/commit/aabd0020e87fb88d97c15da22a1ffcf4e37c1382

**Comment by RubenVerborgh** [comment]
That's a great description, thanks!

(Could you just make sure to put things on `develop` instead of `master` going forward?)

**Comment by mielvds** [comment]
ok, my bad. I fixed a small mistake still.

**Comment by thadguidry** [comment]
@RubenVerborgh you should be doing TBD.  Trunk based development and tagging releases. :)

**Comment by RubenVerborgh** [comment]
Yeah, it's just easy to have `master` to the latest published tag, so the README documentation on GitHub is in sync with what's on npm. `develop` is our trunk.

**Comment by thadguidry** [comment]
@RubenVerborgh lol, ok.  in that case... drink more "beaker" water. :)
