### ISSUE TITLE
question : http link redirection

### ISSUE THREAD

**Issue by obkhan** [LinkedDataFragments/Server.js#54]
Can the config.json be used to redirect to another server location as in the description?

**Comment by rubensworks** [comment]
This is not supported at the moment. What exactly would you use this for?

If it is related to original Memento's, you could use the [Memento extension](https://github.com/LinkedDataFragments/Server.js/wiki/Configuring-Memento#add-an-original-resource) for this.

**Comment by rubensworks** [comment]
Considering this resolved, please comment should this not be the case.
