### ISSUE TITLE
Use TransformIterator to support stream-based data sources

### ISSUE THREAD

**Issue by jacoscaz** [LinkedDataFragments/Server.js#55]
Replacing `BufferedIterator` with `TransformIterator` at https://github.com/LinkedDataFragments/Server.js/blob/f5dff0c55a7a46018014c70e12a1e689b0cd662a/lib/datasources/Datasource.js#L109 allows to feed streams (and other iterators, I think) into the `destination` iterator that is passed to the `_executeQuery` method at https://github.com/LinkedDataFragments/Server.js/blob/f5dff0c55a7a46018014c70e12a1e689b0cd662a/lib/datasources/Datasource.js#L125, which in turn is the one that one needs to override in order to implement a custom data source.

In my case, I'm implementing a custom data source to use the `quadstore` module as the backend for a `ldf-server`. As `quadstore` is able to return a stream of quads for any given query, I'd like to feed such streams into the `destination` iterator without having to worry about backpressure management.

As `TransformIterator` extends `BufferedIterator`, this appears to be just a matter of replacing the latter with the former. I have briefly tested this locally and it seems to be working fine. I can do some more testing and submit a PR if you're interested. 

EDIT: the reason why `TransformIterator` is better than `BufferedIterator` for the purpose of feeding an external stream after the iterator has been instantiated is that it supports setting the iterator's source through the `.source` member.

**Comment by RubenVerborgh** [comment]
You're right! I think the original code was just a result of [replacing](https://github.com/LinkedDataFragments/Server.js/commit/3a8a738667d2807ae19fc741f1da4fbecb840af7) the old iterator framework with AsyncIterator. `TransformIterator` is indeed the more idiomatic choice here. Feel free to PR!

**Comment by RubenVerborgh** [comment]
Following up in #56.
