### ISSUE TITLE
Where is "dbpedia2014.hdt" ?

### ISSUE THREAD

**Issue by akuckartz** [LinkedDataFragments/Server.js#60]
The example "config.json" in "README.md" refers to "data/dbpedia2014.hdt" but the README does not tell where that file is available.

**Comment by akuckartz** [comment]
A DBpedia 2015 version of the HDT file is available here (4.7 GB):
http://gaia.infor.uva.es/hdt/dbpedia2015.hdt.gz

See:
http://www.rdfhdt.org/datasets/

But what about DBpedia 2016 ?

**Comment by RubenVerborgh** [comment]
It's just a configuration example really, it's meant to show the syntax of the config file, not really to be instantiated.
