### ISSUE TITLE
Unexpected behavior when requesting pages with nonexistent page numbers

### ISSUE THREAD

**Issue by Callidon** [LinkedDataFragments/Server.js#63]
Hi!

I ran some experiments with the last version of the LDF server (v2.2.2) and I notice some unexpected behaviors when requesting pages with nonexistent page numbers.

In short, if you request a triple pattern with a page number higher than the max page number, triples from the full graph are returned with one triple per page.

I uploaded an example on Amazon AWS: http://ec2-34-208-134-212.us-west-2.compute.amazonaws.com/watDiv_100 with the triple pattern `?s <http://schema.org/contentSize> ?o`. I use a 100k triples version of WatDiv and 100 triples per page in my configuration file.

This triple has 26 pages, so if you access the last page http://ec2-34-208-134-212.us-west-2.compute.amazonaws.com/watDiv_100?predicate=http%3A%2F%2Fschema.org%2FcontentSize&page=26, everything is fine.

However, if you try to access any page above 26, like http://ec2-34-208-134-212.us-west-2.compute.amazonaws.com/watDiv_100?predicate=http%3A%2F%2Fschema.org%2FcontentSize&page=27, unrelated triples are returned with only one triple per page.
Nonetheless, metadata and hypermedia controls are fine so the classic `ldf-client` is not affected by this issue.

**Comment by RubenVerborgh** [comment]
> I notice some unexpected behaviors when requesting pages with nonexistent page numbers.

May I ask how you got to those pages? Any URL not created by following hypermedia controls has undefined behavior :wink:

Can you try installing the latest version of the hdt Node package (v1.4.2) and see if this fixes things? I suspect you're running into this issue: https://github.com/RubenVerborgh/HDT-Node/pull/13

**Comment by Callidon** [comment]
I was playing with page indexes & HDT, but a mistake in my code lead me to these weird pages ;-)

I just tried the latest version of the hdt Node package and the bug evolved: I can always query any page above 26, but now its always returning a page with only the last matching triple.

**Comment by RubenVerborgh** [comment]
Seems like an HDT issue then. Could you please file a reproducible issue at https://github.com/rdfhdt/hdt-cpp/? Thanks!

Also, might be useful to know whether it also occurs with v1.4.0.
