### ISSUE TITLE
Question about memory requirements

### ISSUE THREAD

**Issue by nichtich** [LinkedDataFragments/Server.js#73]
I ran into problems with memory requirements. Initializing 68 data sources (Turtle files) with slightly more than 3 million triples in total results in a "JavaScript heap out of memory" exception. Merging all sources into one large source gives same result. I could get the server running with node option `--max-old-space-size` but it's still slow and the memory consumption seems rather high. Can you give some numbers of expected memory requirements and/or limitations? What do you recommend to server several million triples as LDF?

It looks like large data sets can only be used via SPARQL or external HDT files (or write your own data source that talks to an indexed set of triples, maybe I should do this for BEACON files).

**Comment by RubenVerborgh** [comment]
> What do you recommend to server several million triples as LDF?

HDT.

Turtle is only really for small data sources (ten thousands of triples), as everything is loaded into memory.

**Comment by nichtich** [comment]
Thanks for clarification. This brings me to https://github.com/RubenVerborgh/HDT-Node/issues/17 for writing HDT :smiling_imp: I'll modify my BEACON data source to create RDF on request only to minimize memory requirements.

**Comment by RubenVerborgh** [comment]
RubenVerborgh/HDT-Node#17 is just about writing headers. Creating an HDT file is a simple as `rdf2hdt -f turtle in.ttl out.hdt`; you can run it as an external command for the timing being.

**Comment by nichtich** [comment]
It's not quite as simple as this because rdf2hdt needs to be installed by hand. With rdf2hdt binding to node, Server.js could create HTD files from any data source if needed. Having to check whether data sources could be too large (either each of them or combined) and converting them to HDT is a limitation.

**Comment by RubenVerborgh** [comment]
> It's not quite as simple as this because rdf2hdt needs to be installed by hand.

True—but that's not that hard :wink:

> With rdf2hdt binding to node, Server.js could create HTD files from any data source if needed.

I don't think it's the server's job to create or migrate data sources. This might be the job of a management server, i.e., software that manages one or more server instances. (We have done [something like that](https://ruben.verborgh.org/publications/devocht_iswc_2015/) in the past before.)

> Having to check whether data sources could be too large (either each of them or combined) and converting them to HDT is a limitation.

I'd just use HDT by default. There's no drawback in using it for small sources.

**Comment by nichtich** [comment]
> I don't think it's the server's job to create or migrate data sources. This might be the job of a management server, i.e., software that manages one or more server instances. (We have done something like that in the past before.)

So I'd set up a server [as I described in the wiki](https://github.com/LinkedDataFragments/Server.js/wiki/Deployment-as-Linux-service) and an additional management component to collect/update/convert data sources, register them in `config.json`, and restart the server with `SIGHUP` afterwards. Does this sound reasonable?

Nevertheless, an upper limit of triples in in-memory sources would help to prevent out-of-memory crashes. This could either be hard-coded, configured, and/or derived from `getHeapStatistics().heap_size_limit`. Additional data sources after reaching the limit should be ignored similar to data sources that failed to initialize for other reasons (e.g. broken input file). An out-of-memory exception, in contrast to other errors, will crash the whole server, so the server should take care not killing itself by reading too many triples. Any arguments against extending `MemoryDatasource` with a triple limit and let the initialization fail once the limit has been reached?

**Comment by RubenVerborgh** [comment]
> So I'd set up a server as I described in the wiki and an additional management component to collect/update/convert data sources, register them in config.json, and restart the server with SIGHUP afterwards. Does this sound reasonable?

Makes perfect sense.

> Any arguments against extending MemoryDatasource with a triple limit and let the initialization fail once the limit has been reached?

Yes, the fact that such a limit cannot easily be expressed in number of triples. It depends on the number of different IRIs and literals, as well as their length, and the exact version of Node.js and N3.js used.
