### ISSUE TITLE
Virtuoso back-end results in “The endpoint returned an invalid Turtle response”

### ISSUE THREAD

**Issue by RubenVerborgh** [LinkedDataFragments/Server.js#75]
Received the following question:

> I am trying to configure a LDF server using a generic (Virtuoso) Sparql endpoint (like dbpedia.org), but run into this errore: "The endpoint returned an invalid Turtle response." It's not clear to me what magic is needed to make it work. Is anybody else running the node LDF server with another sparql endpoint than the  'http://dbpedia.restdesc.org/' one from the config.json example file?

**Comment by joachimvh** [comment]
This is potentially caused by using an incorrect sparql endpoint URL. E.g., for dbpedia you need to use `http://dbpedia.org/sparql` and not `http://dbpedia.org`.

**Comment by rubensworks** [comment]
I just tested `config/config-example.json` (with http://dbpedia.restdesc.org/ as entrypoint) on the master branch, server branch and the releases 2.2.2 versions. All of them work just fine for me. I don't run into the mentioned problem.

Does the server output any other errors on the console?
Are you able to reach the entrypoint directly from the machine the LDF server is running on? It's possible that your request doesn't get through somehow.

**Comment by rubensworks** [comment]
> @joachimvh  thanks, I had a closer look at the config file and it did seem to be a misconfiguration issue. It is working now!

Seems to be resolved!

**Comment by RubenVerborgh** [comment]
Could you still post the correct config here?

**Comment by joachimvh** [comment]
What do you mean by correct config? For my testing I replaced the `http://dbpedia.restdesc.org` in `config/config-example.json` with `http://dbpedia.org/sparql` and it worked.

**Comment by RubenVerborgh** [comment]
Okay, thanks!

**Comment by EnnoMeijers** [comment]
To be honest I am still a little puzzled, probably it was a trailing '/' that nailed me, I am using now these config lines and its working!:
   "KB-NBT": {
      "title": "KB Nationale Bibliografie",
      "type": "SparqlDatasource",
      "description": "Nationale Bibliografie van de KB via een Virtuoso back-end",
      "settings": { "endpoint": "http://data.bibliotheken.nl/sparql", "defaultGraph": "http://data.bibliotheken.nl/nbt-schema/"}
