### ISSUE TITLE
Update Dockerfile to use NodeJS 6 or 8

### ISSUE THREAD

**Issue by barthanssens** [LinkedDataFragments/Server.js#77]
Since 4.8 will be EOL end of April, I'd suggest to switch to NodeJS 6 or 8 LTS (docker image will be somewhat bigger)

**Comment by RubenVerborgh** [comment]
Should be 8 LTS.

**Comment by barthanssens** [comment]
NodeJS 8 does produce a warning when building the docker image, though it should be OK(-ish)

`npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead`

Also a few C++ minor warnings on the HDT code, which is somewhat to be expected (should be fixed in the hdt codebase)

**Comment by RubenVerborgh** [comment]
Thanks, following up in #78!
