### ISSUE TITLE
HDT version needs to be updated

### ISSUE THREAD

**Issue by joachimvh** [LinkedDataFragments/Server.js#83]
2 bugs have been found that both can probably be fixed by updating HDT to the latest version. We should check for any breaking changes though between the current version and the latest.

Problem 1: Some triples appear to be missing when requesting all results in a pattern. In the example here this is specifically a pattern with only a bound predicate, this may or may not be related.
When looking at the results [here](http://fragments.dbpedia.org/2015-10/en?subject=&predicate=http%3A%2F%2Fdbpedia.org%2Fproperty%2Fdeveloper&object=&page=217), at the bottom we can see that there are some triples having "List of humble bundles" as subject, but when we go to the next page there are no further results like this, [even though there should be](http://fragments.dbpedia.org/2015-10/en?subject=http%3A%2F%2Fdbpedia.org%2Fresource%2FList_of_Humble_Bundles&predicate=http%3A%2F%2Fdbpedia.org%2Fproperty%2Fdeveloper&object=).

Problem 2: The last triple keeps being repeated when going to a page further than the last one, e.g.: http://fragments.dbpedia.org/2015-10/en?subject=&predicate=http%3A%2F%2Fdbpedia.org%2Fproperty%2Fdeveloper&object=&page=500

**Comment by RubenVerborgh** [comment]
> breaking changes

v2.x switched from callbacks to Promises, so yeah :smile:

**Comment by RubenVerborgh** [comment]
@joachimvh Can you verify whether #84 fixes those two issues?

**Comment by joachimvh** [comment]
It works now :+1:
