### ISSUE TITLE
How to configure the memento in LDF server?

### ISSUE THREAD

**Issue by yesonmect** [LinkedDataFragments/Server.js#86]
Hi, I set up LDF Server with Server.js way these days. And the LDF is fine now, however, when i merge the memento service, i am failed.
I used the config-example-memento.json file and installed the Chrome plugin of memento, now my problem is: I can see different versions of my resources in LDF Server, as i switch to another version with memento, the address will redirect to "http://timetravel.mementoweb.org/timegate//swdf", which is not my local domain. In these link, there have two issues, one is the domain, the other is double "/" after the "timegate".
So can anyone give me some suggestions? Thanks!

**Comment by RubenVerborgh** [comment]
Can you post your configuration file?

**Comment by yesonmect** [comment]
Thank you for your reply My configuration file is following: 
     {
  "title": "Memento-aware server",

  "datasources": {
    "dbpedia2015": {
      "title": "DBpedia 2015",
      "type": "HdtDatasource",
      "settings": {
        "file": "/data/dbpedia2015en.hdt"
      },
      "memento": {
        "interval": ["2014-09-14T11:59:59Z", "2015-04-15T00:00:00Z"]
      }
    },
    "dbpedia2014": {
      "title": "DBpedia 2014",
      "type": "HdtDatasource",
      "settings": {
        "file": "/data/dbpedia2014en.hdt"
      },
      "memento": {
        "interval": ["2013-06-15T11:59:59Z", "2014-09-15T00:00:00Z"]
      }
    }
  },

  "timegates": {
    "baseURL": "/timegate/",
    "mementos": {
      "dbpedia": {
        "versions": [
          "dbpedia2015",
          "dbpedia2014"
        ]
      }
    }
  },

  "prefixes": {
    "rdf":         "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs":        "http://www.w3.org/2000/01/rdf-schema#",
    "xsd":         "http://www.w3.org/2001/XMLSchema#",
    "dc":          "http://purl.org/dc/terms/",
    "foaf":        "http://xmlns.com/foaf/0.1/",
    "dbpedia":     "http://dbpedia.org/resource/",
    "dbpedia-owl": "http://dbpedia.org/ontology/",
    "dbpprop":     "http://dbpedia.org/property/",
    "hydra":       "http://www.w3.org/ns/hydra/core#",
    "void":        "http://rdfs.org/ns/void#"
  }
}

**Comment by mielvds** [comment]
Hi @yesonmect , how are you using the chrome plugin? The swdf is very strange as you have it nowhere in your config

**Comment by yesonmect** [comment]
yes，i use the chrome plugin.
As i change the time to another，the page turned to memento domain，not my locale one.
Can you give me some examples of setting？I use the setting in github，but failed.
Thanks


On 11/08/2018 22:10, mielvds wrote:

Hi @yesonmect , how are you using the chrome plugin? The swdf is very strange as you have it nowhere in your config

**Comment by mielvds** [comment]
what's the url you are starting from?

**Comment by yesonmect** [comment]
cbdb.library.sh.cn
should i config it in properties file？ 


On 11/08/2018 22:17, mielvds wrote:

what's the url you are starting from?

**Comment by mielvds** [comment]
So your LDF server runs at `cbdb.library.sh.cn`? And what about the `/swdf`, where does that come from?

**Comment by mielvds** [comment]
This is both expected and surprising, as the config you posted here only defines two datasets called `dbpedia2014`and `dbpedia2015`. Where did you configure these `swdf`datasets?

**Comment by yesonmect** [comment]
yes，there are the same，and i changed the name of these two version datasets. Now i will start the service，so you can access it a minutes late


On 11/08/2018 22:28, mielvds wrote:

This is both expected and surprising, as the config you posted here only defines two datasets called dbpedia2014and dbpedia2015. Where did you configure these swdfdatasets?

**Comment by yesonmect** [comment]
I have started the ldf server, and the site is: http://cbdb.library.sh.cn:5000
And in ldf server, there have two dataset: dbpedia2014 and dbpedia2015. Then as I query "US/Eastern" in object in dbpedia2015. Next, I use the chrome memento plugin, the page redirect to "http://timetravel.mementoweb.org/timegate//dbpedia?subject=&predicate=&object=%22US%2FEastern%22", not "http://cbdb.library.sh.cn:5000/timegate/dbpedia?....."

**Comment by mielvds** [comment]
My best guess is that the plugin cannot parse the relative URL in the link header.

Try adding the base URL in your config:

`"baseURL": "http://cbdb.library.sh.cn:5000/",`

**Comment by yesonmect** [comment]
I added it as following:
 "title": "Memento-aware server",
  "baseURL": "http://cbdb.library.sh.cn:5000/",
  "datasources": {
    "dbpedia2015": {

Is it right? Now the page redirect to : http://timetravel.mementoweb.org/timegate/http://cbdb.library.sh.cn:5000/dbpedia?subject=&predicate=&object=%22US%2FEastern%22

**Comment by mielvds** [comment]
no that's not right, very strange. In any case, I believe this is a bug in the memento plugin, so better contact them.
