### ISSUE TITLE
Timegate not accessible on Memento server local deployment

### ISSUE THREAD

**Issue by vemonet** [LinkedDataFragments/Server.js#87]
We are trying to deploy a Memento-aware Linked Data Fragments Server using Docker.

We are using the exact same config-example-memento.json file that is provided as example with the repository (see below).

The server is running and working, we have no problem to access and browse it at http://localhost:3000/ 

But we cannot perform temporal queries using Memento. Using the following query ends up in a 404:
```shell
curl -IL -H "Accept-Datetime: Wed, 15 Apr 2013 00:00:00 GMT" http://localhost:3000/timegate/http://dbpedia.org/page/English
```

When the exact query on your production environment works:
```shell
curl -IL -H "Accept-Datetime: Wed, 15 Apr 2013 00:00:00 GMT" http://dbpedia.mementodepot.org/timegate/http://dbpedia.org/page/English
```

I noticed that calling http://dbpedia.mementodepot.org/timegate/ results in a code 302 and that the accept-datetime is resolved. 
But http://localhost:3000/timegate/ directly trigger a 404. Meaning that the timegate server is not properly deployed on the local instance, or that it is located at another URL. Note that we are not facing any error.

There is nothing mentionned about it in the Configuring Memento wiki (https://github.com/LinkedDataFragments/Server.js/wiki/Configuring-Memento), it seems like it would be directly deployed on http://localhost:3000/

**Do you have any idea which part are we missing to access the timegate?**

config.json:
```json
{
  "title": "Memento-aware server",

  "datasources": {
    "dbpedia2015": {
      "title": "DBpedia 2015",
      "type": "HdtDatasource",
      "settings": {
        "file": "/data/dbpedia2015en.hdt"
      },
      "memento": {
        "interval": ["2014-09-14T11:59:59Z", "2015-04-15T00:00:00Z"]
      }
    },
    "dbpedia2014": {
      "title": "DBpedia 2014",
      "type": "HdtDatasource",
      "settings": {
        "file": "/data/dbpedia2014en.hdt"
      },
      "memento": {
        "interval": ["2013-06-15T11:59:59Z", "2014-09-15T00:00:00Z"]
      }
    }
  },

  "timegates": {
    "baseURL": "/timegate/",
    "mementos": {
      "dbpedia": {
        "versions": [
          "dbpedia2015",
          "dbpedia2014"
        ]
      }
    }
  },

  "prefixes": {
    "rdf":         "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs":        "http://www.w3.org/2000/01/rdf-schema#",
    "xsd":         "http://www.w3.org/2001/XMLSchema#",
    "dc":          "http://purl.org/dc/terms/",
    "foaf":        "http://xmlns.com/foaf/0.1/",
    "dbpedia":     "http://dbpedia.org/resource/",
    "dbpedia-owl": "http://dbpedia.org/ontology/",
    "dbpprop":     "http://dbpedia.org/property/",
    "hydra":       "http://www.w3.org/ns/hydra/core#",
    "void":        "http://rdfs.org/ns/void#"
  }
}
```

**Comment by mielvds** [comment]
Hi! Can you reach the mementos dbpedia2014 & dbpedia2015?

**Comment by vemonet** [comment]
Thanks a lot for this quick and detailed answer!
Yes I figured it out for the JSON structure and the proxy. I was just missing the cURL to query, since it is different from the example given for the production environment 

Beside of that the installation documentation was good and it went smoothly. If you can show an example cURL query to perform on the deployed instance it would be perfect!
Something like:
```shell
 curl -IL -H "Accept-Datetime: Wed, 15 Apr 2013 00:00:00 GMT" http://localhost:3000/timegate/dbpedia?subject=http%3A%2F%2Fdbpedia.org%2Fpage%2FEnglish
```
