### ISSUE TITLE
Some data can't be found with defined url?

### ISSUE THREAD

**Issue by miranda-zhang** [LinkedDataFragments/Server.js#92]
My data looks like example below :
```ttl
<https://w3id.org/cocoon/data/v1.0.1/Measurement/DownlinkSpeed-1-128-KB/StorageService/Gcloud/150.203.213.249/lat=-35.271475/long=149.121434/2019-02-26T07%3A14%3A19.932Z/australia-southeast1>
        a                          cocoon:Measurement ;
        sosa:hasFeatureOfInterest  <https://w3id.org/cocoon/data/v1.0.1/DownlinkSpeed-1-128-KB/StorageService/Gcloud/australia-southeast1> ;
        sosa:hasResult             [ a                        schema:TypeAndQuantityNode ;
                                     schema:amountOfThisGood  11.22e0 ;
                                     schema:unitCode          unit:MegabitsPerSecond
                                   ] ;
        sosa:madeBySensor          <https://w3id.org/cocoon/data/v1.0.1/Device/150.203.213.249/lat=-35.271475/long=149.121434> ;
        sosa:resultTime            "2019-02-26T07:14:19.932Z"^^xsd:dateTime .
```
But I can't find it on my server with
https://w3id.org/cocoon/data/v1.0.1/Measurement/DownlinkSpeed-1-128-KB/StorageService/Gcloud/150.203.213.249/lat=-35.271475/long=149.121434/2019-02-26T07%3A14%3A19.932Z/australia-southeast1

The file used on my server is
https://github.com/miranda-zhang/cloud-computing-schema/blob/ldf-server/v1.0.1/gcloud/v1.0.1/downlink_latency.ttl

**Comment by rubensworks** [comment]
Your URL is invalid.

If you enter your subject into the TPF for manually, you will find the following results:
http://35.231.131.100:5000/cocoon_v1.0.1?subject=https%3A%2F%2Fw3id.org%2Fcocoon%2Fdata%2Fv1.0.1%2FMeasurement%2FDownlinkSpeed-1-128-KB%2FStorageService%2FGcloud%2F150.203.213.249%2Flat%3D-35.271475%2Flong%3D149.121434%2F2019-02-26T07%253A14%253A19.932Z%2Faustralia-southeast1

I assume you are encoding the query parameters yourself, and it seems you are not encoding `:` correctly into `%3A`.

**Comment by miranda-zhang** [comment]
Thanks!
I'm still trying to figure out [how to encode my URL with .htaccess](https://serverfault.com/questions/961457/htaccess-rule-to-encode-only-some-captured-group)
