### ISSUE TITLE
reverse proxy: consider support for FORWARDED or X-FORWARDED-HOST header

### ISSUE THREAD

**Issue by nvdk** [LinkedDataFragments/Server.js#95]
Currently the instructions for running behind a reverse proxy recommend setting the Host header so that the LDF server can generate the correct uri's. Would you consider using a better suited header like the [FORWARDED](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) header or the[ X-FORWARDED-HOST](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host) header (the defacto standard)?

Reverse proxies typically already set this header by default (requiring less configuration), but besides that overwriting the host header may also break http logging solutions that rely on a correct host header to properly monitor and catalog HTTP traffic between a reverse proxy and it's backend services.

**Comment by rubensworks** [comment]
Support for Forward headers has been added a while ago: https://github.com/LinkedDataFragments/Server.js/pull/50

Does that solve your use case @nvdk?

**Comment by nvdk** [comment]
Thanks for the reply, I've had a look and that seems to work as expected!  It would be useful to add this information to the README, that would make it easier to discover and should make it easier to deprecate the setting of the host Header later on.
